# Generated by Django 3.0.2 on 2020-10-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='катигория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описания')),
                ('photo', models.ImageField(upload_to='', verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='album/', verbose_name='фото')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_router.Product')),
            ],
        ),
    ]
