# Generated by Django 3.0.2 on 2020-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_router.Category', verbose_name='катигория'),
        ),
    ]
