# Generated by Django 3.0.2 on 2020-10-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0005_auto_20201030_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='secur',
            new_name='safety',
        ),
    ]
