# Generated by Django 3.0.2 on 2020-10-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0008_product_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_quantity',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantities', models.IntegerField()),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_router.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_router.Product')),
            ],
        ),
    ]
