# Generated by Django 3.0.2 on 2020-11-01 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0010_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
