# Generated by Django 3.0.2 on 2020-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0011_auto_20201101_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
    ]
