# Generated by Django 3.0.2 on 2020-11-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0014_auto_20201105_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
