# Generated by Django 3.0.2 on 2020-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0016_auto_20201105_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
