# Generated by Django 3.0.2 on 2020-11-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0017_product_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_category', to='shop_router.Category'),
        ),
    ]
