# Generated by Django 3.0.2 on 2020-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0018_category_children_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_set', to='shop_router.Category', verbose_name='катигория'),
        ),
    ]
