# Generated by Django 3.0.2 on 2020-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0019_auto_20201118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_router.Category', verbose_name='катигория'),
        ),
    ]
