# Generated by Django 3.0.2 on 2020-11-20 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_router', '0021_auto_20201118_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='brand',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
